PROG = scam-back
CC = cc
CCFLAGS = -O2 -D_REENTRANT
CFLAGS = -I/usr/include/
LDFLAGS =  -L/usr/lib
LIBS = -lmilter -pthread
SRC = scam-back.c util.c tcp.c
$(PROG): ${SRC}
		${CC} ${CCFLAGS} ${SRC} ${CFLAGS} ${LDFLAGS} ${LIBS} -o ${PROG}
clean:
	-rm -f $(PROG) *.o *.core
