PROG = scam-back
CC = cc
CCFLAGS += -O2 -D_REENTRANT -DSOLARIS
CFLAGS = -I/usr/local/include/
LDFLAGS =  -L/usr/local/lib
LIBS = -lmilter -lresolv -lsocket -lnsl -lpthread
SRC = scam-back.c util.c tcp.c
$(PROG): ${SRC}
		${CC} ${CCFLAGS} ${SRC} ${CFLAGS} ${LDFLAGS} ${LIBS} -o ${PROG}
clean:
	-rm -f $(PROG) *.o *.core
